version: '3.4'

services:
  database:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"

volumes:
  db_data:
